### ISSUE TITLE
Auto collate restarts

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#124]
@rmholmes would like to have a config flag to auto collate restarts. Now collate config has been cleaned up should be quite straightforward

**Comment by rmholmes** [comment]
Hi Aidan,

Thanks for the action on this. 

For my analysis, I only need the restarts in order to analyse the next year of output. So, for example, I would be happy if restart005 was collated at the same time as output006. This would also solve both your points 1 and 2, as the model run for output006 would be restarted from uncollated restart005. I can't see an obvious problem with this - apart from wasted collating of restarts if a user has restart_freq other than 1. But you guys would know better than me.

PS: The reason I use restarts for analysis is because I need to know the state of the temperature field at the initialization time in order to calculate how it changes over the first diagnostic accumulation period (usually a month). I could also get this from the previous output - but this is not always available (e.g. a new run or the first year of a run branched from somewhere else where the right diagnostics weren't saved).

**Comment by aidanheerdegen** [comment]
Thanks @rmholmes. I agree that collating when cleaning up restarts seems the obvious way forward.

Thanks for the feedback.

**Comment by aidanheerdegen** [comment]
For some reason https://github.com/marshallward/payu/pull/125 was overwritten with the old code so this stopped working.

I have redone it here:

https://github.com/marshallward/payu/pull/158

but applied the collation to the previous restart directory. This solves all the issues noted above I believe and seems a relatively clean solution.

Once that PR is merged I think we can close this Issue.

**Comment by aidanheerdegen** [comment]
Ok, this is now merged. To invoke, need to use `restart: True` in the new `collate` `dict` options, e.g.
```yaml
collate:
    enable: True
    walltime: 4:00:00
    mem: 30GB
    ncpus: 1
    queue: copyq
    flags: -n4 -z -m -r
    exe: mppnccombine
    restart: True
```

**Comment by aidanheerdegen** [comment]
ping @rmholmes

**Comment by rmholmes** [comment]
Thanks Aidan, I'll give it a go next time I run

**Comment by aidanheerdegen** [comment]
You'll need to ask to make sure you've using a `payu` version with this code change. It is not currently installed anywhere.
