### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#127]
Need to be able to run payu as part of a conda environment. This is essential for CMS support of payu at NCI, but it is also beneficial for using payu on other systems. 

Also as payu gets more dependencies it becomes more cumbersome to install as a stand-alone module.

The CMS team will undertake to provide a payu package in our conda channel

https://anaconda.org/coecms

**Comment by marshallward** [comment]
Making very good progress on this, my local version appears to successfully run payu under the user's target python version in the shell, and passing all environment variables (`-V`) appears to work.

I am trying to pare down the environment variables, in order to make sure that we're not just accidentally (or deliberately) passing entire modules environments across sessions, but will hopefully progress on this very soon.

Also, I have integrated increase support for Python 2.6, which I'm sure no one cares about but me.  But it could improve stability for some users.

**Comment by aidanheerdegen** [comment]
You mentioned you were working on this, but I thought I should make it an explicit goal, which you can then tick off! Win win.

**Comment by marshallward** [comment]
Now that we support Python 3 and are using `entry_point` for the runscripts, one might say that we now support conda.  So we can close this ticket.

But since there is no conda install anywhere on Raijin, I am not sure if we should make the final step and install a conda-friendly version somewhere.

**Comment by aidanheerdegen** [comment]
When you say there is no conda install, you mean a central one?

**Comment by marshallward** [comment]
Aidan appears to have successfully installed and run this using a conda bin, so I think we can close this.
